####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-adjoint
Description: Adjoint-based gradients for the OPM flow simulator
Version: 2026.10-pre
Label: 2026.10-pre
Maintainer: halvor.m.nilsen@sintef.no
MaintainerName: Halvor M. Nilsen
Url: http://opm-project.org
Depends: dune-istl (>= 2.9) opm-common opm-grid opm-simulators
